version: '3.8'

services:
  db:
    image: mysql:8.0
    platform: linux/arm64
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - node-network

  node:
    build: ./node
    container_name: node
    restart: always
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - node-network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    platform: linux/arm64
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network
    depends_on:
      - node

networks:
  node-network:

volumes:
  mysql_data:
