version: '3.8'

services:
  db:
    image: mysql:5.7
    # command: --innodb-use-native-aio=0
    platform: linux/x86_64
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    command: --innodb-use-native-aio=0 && --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - node-network

  node:
    build: ./node
    platform: linux/x86_64
    container_name: node
    restart: always
    command: sh -c "npm install && npm start"
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - node-network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    platform: linux/x86_64
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network
    depends_on:
      - node

networks:
  node-network:

volumes:
  mysql_data:
